<?php
/*
 * ************** CAUTION **************
 *
 * DO NOT EDIT THIS FILE as it will be overridden by Central as part of
 * the installation/update process.
 *
 * ************** CAUTION **************
 */

$API->config(array(
    'templates.path' => 'Views',
    'database.host' => 'your_host',
    'database.name' => 'your_database',
    'database.user' => 'your_user',
    'database.pass' => 'your_passw00rd',
));
 
// PULSE Framework Content Type
$API->contentType('text/html; charset=utf-8');

// PDO Database connection
$db = new PDO('mysql:host=' . $API->config('database.host') . 
             ';dbname=' . $API->config('database.name') . 
             ';charset=utf8', $API->config('database.user'), $API->config('database.pass'));
